spring.datasource.url=jdbc:postgresql://localhost:5432/polya
spring.datasource.username=postgres
spring.datasource.password=235923

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Fayl yuklash hajmini production darajasiga ko'tarish
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=50MB

# Vaqtinchalik fayllarni xotirada parsing qilish chegarasi
spring.servlet.multipart.file-size-threshold=2KB